server:
    port: 8001

spring:
    application:
        name: service-edu
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/my_gzs?serverTimezone=GMT%2B8
        username: root
        password: 1234
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    profiles:
        active: dev
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl